[book]
title = "Goudham's Digital Garden"
authors = ["Goudham Suresh"]
description = "A digital garden to store my ideas and thoughts"
language = "en"
multilingual = false
src = "digital_garden"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
no-section-label = true
git-repository-url = "https://github.com/goudham-me/homepage"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/goudham-me/homepage/edit/main/src/{path}"

[output.html.fold]
enable = true
level = 4