[book]
title = "Goudham's Digital Garden"
authors = ["Goudham Suresh"]
description = "A digital garden to store my ideas and thoughts"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "ayu"